bellshade/Javascript

conversion/BinaryToDecimal.js
conversion/DecimalToOctal.js

koversi bilangan desimal ke octal
- ``os`` = ``Linux``

add: bilangan desimal ke octal

---

data_structure/filterDuplicateArray.js

Menambahkan penyelesaian duklikasi value pada array
- `os` = `linux `

add: menambahkan algoritma filter duplikasi array

---

data_structure/filterDuplicateArray.js
data_structure/filterEvenOddArray.js

Menambahkan filter genap ganjil pada Array

---

data_structure/filterDuplicateArray.js
data_structure/filterEvenOddArray.js

fix description code

---

other/includedInArray.js

add: menambahkan contoh penggunaan includes

---

chiper/caesar.js

add: menambahkan chiper caesar (sandi geser)

---

other/someValueInArray.js

add: menambahkan contoh penggunaan some

---

chiper/base64.js

add: menambahkan mengenkode tulisan ke format base64

---

chiper/affine.js

add: menambahkan affine cipher

---

other/getMean.js

add: menambahkan algoritma menentukan mean

---

chiper/affine.js

Add: menambah affine cipher

---

README.md
shorting_algorithm/bubbleshort.js
sorting_algorithm/bubblesort.js

add: menambahkan algoritma bubble sort

---

other/sortPeopleName.js

add: menambahkan contoh penggunaan localeCompare untuk menyortir daftar nama

---

looping/break.js
looping/continue.js
looping/patternWithNumber.js

Add looping

---

basic/looping/recursiveLoop.js

add: recursiveLoop.js

---

other/palindrome.js

add: palindrome

---

other/getFactorial.js

Get factorial

---

basic/string_and_string_manipulation/README.md
basic/string_and_string_manipulation/anotherStringDeclaration.js
basic/string_and_string_manipulation/stringManipulation.js

Closes #29 and #28
@bellshade/javascript-team 

String dan Rekayasa String

---

other/convertTitleToSlug.js

add: convert title ke slug

---

README.md
basic/010_array_manipulation/README.md
basic/010_array_manipulation/map.js
basic/010_array_manipulation/push.js
basic/README.md

add: array manipulation

---

basic/003_operator/README.md
basic/003_operator/inOperator.js

Menambahkan sub materi operator

---

sorting_algorithm/quickSort.js

Menambahkan Algoritma Quick Sort

---

basic/005_conditioning/README.md
basic/005_conditioning/conditionalStatements.js

fix: add switch case

---

conversion/TimeConversion.js

add: time conversion 24 hours

---

other/convertTitleToSlug.js
search/data-test.json
search/searchEngine.js
search/search_engine.js
sorting_algorithm/quickSort.js

Closes 
- `os` = `linux & windows`

add: menambahkan search_engine.js

---

data_structure/undirectedGraph.js

add: menambahkan algoritma undirectedGraph

---

validation/ipAddressValidation.js

Menambahkan validasi IP Address 

---

validation/phoneNumberValidation.js

Menambahkan validasi untuk cek No HP

---

cipher/rot13.js

add: menambahkan algoritma rot13 pada folder chiper

---

basic/002_variable_datatype/README.md
basic/002_variable_datatype/typeOf.js

Menambahkan typeOf

---

es6/001_introduction/README.md
es6/002_variable/README.md
es6/002_variable/variable.js
es6/003_arrow_function/README.md
es6/003_arrow_function/arrowFunction.js

Closes 
@bellshade/javascript-team 

add: es6 dan isi foldernya

---

basic/012_basic_program/recursive.js
cipher/rot13.js
conversion/NumberToRupiah.js
conversion/TimeConversion.js
yarn.lock

Closes #80 
@bellshade/javascript-team 

Recursive program

---

CONTRIBUTING.md
cipher/rot13.js
conversion/NumberToRupiah.js
conversion/TimeConversion.js
package.json
validation/emailValidation.js

npm script fix

---

CONTRIBUTING.md
basic/002_variable_datatype/README.md
basic/003_operator/README.md
basic/003_operator/comparisonOperators.js
basic/003_operator/inOperator.js
basic/004_string_and_string_manipulation/anotherStringDeclaration.js
basic/005_conditioning/README.md
basic/007_looping/README.md
basic/007_looping/forWhileLoop.js
basic/008_function/README.md
basic/011_classes/classes.js
other/includedInArray.js
other/someValueInArray.js
validation/ipAddressValidation.js

Menambahkan Contoh Looping dan Memperbaiki Ejaan Bahasa Indonesia

---

es6/005_default_parameter/README.md
es6/005_default_parameter/defaultParameter.js

feat: menambahkan pembahasan es6 tentang default parameter

---

es6/005_for_of_loop/README.md
es6/005_for_of_loop/forOfLoop.js

docs: menambahkan dokumentasi for of loop pada es6

---

.mergify.yml

Closes 
update bot untuk tambah label dan request review dari maintainer sesuai dengan file yng akan ditambah atau dirubah
tidak memakai testing

feat: menambahkan automatic bot

---

learn/DOM/005_Events/README.md
learn/DOM/005_Events/index.html
learn/DOM/005_Events/script.js

DOM: events

---

algorithm/search/searchPrimeNumber.js

feat: menambahkan algoritma searchPrime

---

algorithm/sorting_algorithm/vowelSort.js

feat: menambahkan algoritma vowelSort

---

algorithm/data_structure/chunkifyArray.js
learn/Basic/008_function/README.md
learn/Basic/008_function/functionAnonymous.js
learn/Basic/008_function/functionCallback.js

Menambahkan materi anonymous function dan algoritma chunkifyArray

---

learn/DOM/006_Event_Listener/README.md
learn/DOM/006_Event_Listener/index.html
learn/DOM/006_Event_Listener/script.js

docs: menambahkan materi DOM Event Listener

---

learn/Basic/001_hello_world/README.md
learn/Basic/002_variable_datatype/README.md
learn/Basic/003_operator/README.md
learn/Basic/004_string_and_string_manipulation/README.md
learn/Basic/005_conditioning/README.md
learn/Basic/006_arithmetic_operation/README.md
learn/Basic/007_looping/README.md
learn/Basic/008_function/README.md
learn/Basic/009_array/README.md
learn/Basic/010_array_manipulation/README.md
learn/Basic/011_object/README.md
learn/Basic/012_object_manipulation/README.md
learn/Basic/013_classes/README.md
learn/Basic/014_strict_mode/README.md

docs: menambahkan nav di materi Basic

---

learn/Basic/005_conditioning/conditionalStatements.js
learn/Basic/014_strict_mode/strictMode.js
package-lock.json
package.json
server/public/js/common.js
server/utils/markdownParser.js
yarn.lock

fix: menambahkan kembali package yang sebelumnya diubah

---

learn/DOM/001_Introduction/README.md
learn/DOM/002_DOM_Nodes/README.md
learn/DOM/003_Collections/README.md
learn/DOM/004_Methods/README.md
learn/DOM/005_Events/README.md
learn/DOM/006_Event_Listener/README.md
learn/DOM/007_Traversal/README.md
learn/DOM/008_Event_Bubbling_and_Capturing/README.md
learn/DOM/README.md
learn/ES6/001_introduction/README.md
learn/ES6/002_variable/README.md
learn/ES6/003_arrow_function/README.md
learn/ES6/004_template_literals/README.md
learn/ES6/005_tagged_templates/README.md
learn/ES6/006_destructuring_assignment/README.md
learn/ES6/007_for_of_loop/README.md
learn/ES6/008_spread_operator/README.md
learn/ES6/009_function_rest_parameter/README.md
learn/ES6/010_default_parameter/README.md
learn/ES6/011_map_objects/README.md
learn/ES6/012_string_includes/README.md
learn/ES6/013_string_helpers/README.md

docs: menambahkan nav di folder DOM dan ES6

---

learn/OOP/004_Abstraction/README.md
learn/OOP/004_Abstraction/abstraction.js

Menambahkan materi OOP Abstraction

---

learn/OOP/006_Polymorphism/README.md
learn/OOP/006_Polymorphism/polymorphism.js

Menambahkan materi Object Oriented Programming tentang Polymorphism

---

learn/Basic/003_operator/README.md
learn/Basic/003_operator/doubleBangOperator.js

Closes 
saya menggunakan (im using):

docs: menambahkan operator double bang

---

learn/Basic/README.md
learn/DOM/README.md
learn/ES6/README.md
learn/WebApi/README.md

Menambahkan preview pembelajaran di folder `ES6` dan `WebApi`

---

package.json

fix: mengignore peer deps popperjs yang tidak dipakai bootstrap

---

algorithm/validation/isSortedChecking.js

add: menambahkan algoritma baru

---

learn/WebApi/Console/README.md
learn/WebApi/Console/index.html
learn/WebApi/README.md

add: menambahkan materi Console Object Methods

---

learn/WebApi/GeoLocation/README.md
learn/WebApi/GeoLocation/geolocation.js
learn/WebApi/GeoLocation/index.html

feat: add geolocation status

---

algorithm/WebRelated/preventPaste/index.html
algorithm/WebRelated/preventPaste/prevent.js

Closes 
Fungsi ini berguna untuk mencegah agar user tidak bisa mempaste di inputan di form website kita.

feat: menambahkan fungsi untuk melarang mem-paste

---

algorithm/WebRelated/RealtimeWindowSizeDetection/detector.js
algorithm/WebRelated/RealtimeWindowSizeDetection/index.html

Closes 
Algoritma ini berguna untuk mendeteksi ukuran window browser secara realtime.

add: algoritma untuk deteksi ukuran window browser secara realtime

---

README.md

docs: memperbaiki URL yang salah di contoh "Navbar"

---

algorithm/math/factorTree.js

- `os` = `linux` (di gitpod dengan node 17)

feat: algoritma untuk menemukan faktor faktor dari suatu bilangan

---

algorithm/WebRelated/WordsAndCharsCounter/counter.js
algorithm/WebRelated/WordsAndCharsCounter/index.html

Program ini berguna untuk menghitung jumlah kata dan karakter secara realtime.
Label HACKTOBERFEST-ACCEPTED

add: program hitung jumlah kata dan karakter secara realtime

---

algorithm/WebRelated/preventCopy/index.html
algorithm/WebRelated/preventCopy/prevent.js

Closes 
Fungsi ini berguna untuk mencegah agar user tidak bisa melakukan copy di tulisan yang ada di website kita.

feat: menambahkan fungsi agar teks tidak bisa di-copy

---

algorithm/other/nameShortener.js

Closes 
Label HACKTOBERFEST-ACCEPTED

feat: menambahkan algoritma penyingkatan nama

---

learn/Basic/010_array_manipulation/README.md
learn/Basic/010_array_manipulation/every.js
learn/Basic/010_array_manipulation/findIndex.js

add: array manipulation - findIndex

---

README.md

Saya mengganti base url untuk visitor badge karena error beberapa waktu lalu.
- `os` = `Android`

fix: visitor badge

---

algorithm/WebRelated/disableRightClick/index.html
algorithm/WebRelated/disableRightClick/prevent.js

Closes 
Fungsi ini berguna untuk mencegah agar user tidak bisa mengklik kanan pada website kita.

feat: menambahkan fungsi untuk menonaktifkan klik kanan di website kita

---

learn/Basic/008_function/README.md
learn/Basic/008_function/functionScope.js
learn/Functional/007_Keyword_This/README.md
learn/Functional/007_Keyword_This/example.js

docs: Menambahkan Dokumentasi Function Scope dan Keyword This

---

learn/ES6/013_set_operators/README.md
learn/ES6/013_set_operators/setOperators.js
yarn.lock

docs: menambahkan set operators

---

algorithm/cipher/porta.js

feat: algoritma porta cipher

---

learn/Basic/003_operator/README.md
learn/Basic/006_looping/README.md
learn/Basic/009_array/README.md

docs: menambahkan dan mengubah dokumentasi
